chore: remove leftover infinity loop test code (#4197)
Even the simple scenario `<Field.Number />` can result in:

```
Error: Infinity loop detected and stopped.
    at useFieldProps (http://localhost:8002/src_extensions_forms_Form_index_ts.iframe.bundle.js:6112:11)
    at NumberComponent (http://localhost:8002/src_extensions_forms_index_ts.iframe.bundle.js:1878:49)
```


Not sure what the cause is, I just randomly type random values, then
remove them all(using command + A -> backspace) before entering new
random values:



https://github.com/user-attachments/assets/7168d150-0119-4f21-9894-281d6e7982fb


Here's one where I only enter 1 and backspace * repeat:




https://github.com/user-attachments/assets/9c641c5a-9b70-4d8d-bda1-e4ba9b75a9fc

---------

Co-authored-by: Tobias Høegh <tobias@tujo.no>