feat: upgrade internal Node.js version to latest LTS (#5400)
Motivation; this error message:
https://github.com/dnbexperience/eufemia/actions/runs/17038114990/job/48295272965?pr=5399

I'm not aware of any downsides or issues this upgrade could cause.
Also, I think its time to make the move.

**What about the current Node.js version?**
I tried to run v24, but Gatsby seems to have an issue:

```log
"length" is outside of buffer bounds



  Error: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
  
  - buffer:1073 Buffer.utf8Write
    node:internal/buffer:1073:13
  
  - node.cjs:1202 Packr.encodeUtf8
    [eufemia]/[msgpackr]/dist/node.cjs:1202:18
  
  - node.cjs:1491 pack
    [eufemia]/[msgpackr]/dist/node.cjs:1491:15
  
  - node.cjs:1859 Packr.writeRecord
    [eufemia]/[msgpackr]/dist/node.cjs:1859:6
  
  - node.cjs:1589 pack
    [eufemia]/[msgpackr]/dist/node.cjs:1589:7
```